version: '3.8'

services:
  zookeeper1:
    image: zookeeper:3.8
    hostname: zookeeper1
    container_name: zookeeper1
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: |
        server.1=zookeeper1:2888:3888
        server.2=zookeeper2:2888:3888
        server.3=zookeeper3:2888:3888
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 15
      ZOO_SYNC_LIMIT: 10
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok,stat,srvr"
      ZOO_CFG_EXTRA: |
        clientPort=2181
    volumes:
      - ./zk-data/zookeeper1:/data
    networks:
      - solr-net

  zookeeper2:
    image: zookeeper:3.8
    hostname: zookeeper2
    container_name: zookeeper2
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: |
        server.1=zookeeper1:2888:3888
        server.2=zookeeper2:2888:3888
        server.3=zookeeper3:2888:3888
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 15
      ZOO_SYNC_LIMIT: 10
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok,stat,srvr"
      ZOO_CFG_EXTRA: |
        clientPort=2181
    volumes:
      - ./zk-data/zookeeper2:/data
    networks:
      - solr-net

  zookeeper3:
    image: zookeeper:3.8
    hostname: zookeeper3
    container_name: zookeeper3
    restart: always
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: |
        server.1=zookeeper1:2888:3888
        server.2=zookeeper2:2888:3888
        server.3=zookeeper3:2888:3888
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 15
      ZOO_SYNC_LIMIT: 10
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok,stat,srvr"
      ZOO_CFG_EXTRA: |
        clientPort=2181
    volumes:
      - ./zk-data/zookeeper3:/data
    networks:
      - solr-net

  solr1:
    image: solr-custom-minimalv1:9.6
    container_name: solr1
    hostname: solr1.local
    restart: always
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      - SOLR_HOST=solr1.local                # Force Solr internal hostname
      - SOLR_SSL_CHECK_PEER_NAME=true        # Enforce peer verification (once fixed)
      - SOLR_JAVA_MEM=-Xms1g -Xmx1g
      - ZK_HOST=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - SOLR_SSL_ENABLED=true
      - SOLR_SSL_KEY_STORE=/opt/solr/server/etc/solr-ssl.keystore.p12
      - SOLR_SSL_KEY_STORE_PASSWORD=secret
      - SOLR_SSL_TRUST_STORE=/opt/solr/server/etc/solr-ssl.keystore.p12
      - SOLR_SSL_TRUST_STORE_PASSWORD=secret
      - SOLR_USER=solr
      - SOLR_PASS=SolrRocks
    volumes:
      - ./solr-data/solr1:/var/solr
      - ./ssl/solr-ssl.keystore.p12:/opt/solr/server/etc/solr-ssl.keystore.p12
      - ./security/security.json:/var/solr/data/security.json
      - ./clusterprops/clusterprops.json:/var/solr/data/clusterprops.json
    ports:
      - "8983:8983"
    #entrypoint: ["/docker-entrypoint.sh"]
    networks:
      - solr-net

  solr2:
    image: solr-custom-minimalv1:9.6
    container_name: solr2
    hostname: solr2.local
    restart: always
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      - SOLR_HOST=solr2.local                # Force Solr internal hostname
      - SOLR_SSL_CHECK_PEER_NAME=true        # Enforce peer verification (once fixed)
      - SOLR_JAVA_MEM=-Xms1g -Xmx1g
      - ZK_HOST=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - SOLR_SSL_ENABLED=true
      - SOLR_SSL_KEY_STORE=/opt/solr/server/etc/solr-ssl.keystore.p12
      - SOLR_SSL_KEY_STORE_PASSWORD=secret
      - SOLR_SSL_TRUST_STORE=/opt/solr/server/etc/solr-ssl.keystore.p12
      - SOLR_SSL_TRUST_STORE_PASSWORD=secret
      - SOLR_USER=solr
      - SOLR_PASS=SolrRocks
    volumes:
      - ./solr-data/solr2:/var/solr
      - ./ssl/solr-ssl.keystore.p12:/opt/solr/server/etc/solr-ssl.keystore.p12
      - ./security/security.json:/var/solr/data/security.json
      - ./clusterprops/clusterprops.json:/var/solr/data/clusterprops.json
    ports:
      - "8984:8983"
    #entrypoint: ["/docker-entrypoint.sh"]
    networks:
      - solr-net

networks:
  solr-net:
    driver: bridge